onlyBuiltDependencies:
  - "better-sqlite3"
  - "sharp"
  - "@tailwindcss/oxide"
  - "simple-git-hooks"
  - "unrs-resolver"

ignoredBuiltDependencies:
  - "vue-demi"
  - "esbuild"
  - "@parcel/watcher"
